# Generated by Django 4.2.5 on 2023-11-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uva_maps", "0002_feedback_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
